import { useState, type ReactNode } from 'react';
import { ChevronDown, ChevronUp, Database, ExternalLink, FileSearch } from 'lucide-react';
import { api, type Coverage, type RunMode, type SourceRecord } from '../api/backendClient';
import { errorMessage, formatTime } from '../lib/format';

const STATUS_TONE: Record<string, string> = {
  queued: 'badge-low', running: 'badge-medium', reviewing: 'badge-medium', completed: 'badge-success',
  partial: 'badge-high', failed: 'badge-critical', interrupted: 'badge-high',
  open: 'badge-high', in_progress: 'badge-medium', verified: 'badge-success', dismissed: 'badge-low',
  draft: 'badge-low', approved: 'badge-success', committed: 'badge-success', needs_review: 'badge-high',
  revise: 'badge-high', rejected: 'badge-critical',
};

export function StatusBadge({ status }: { status: string }) {
  return <span className={`badge ${STATUS_TONE[status] ?? 'badge-outline'}`}>{status.replace(/_/g, ' ')}</span>;
}

export function PriorityBadge({ priority }: { priority: string }) {
  const tone = priority === 'high' ? 'badge-high' : priority === 'medium' ? 'badge-medium' : 'badge-low';
  return <span className={`badge ${tone}`}>{priority} verification priority</span>;
}

export function ModeBadge({ mode, model }: { mode: RunMode; model?: string | null }) {
  return mode === 'live_model'
    ? <span className="badge badge-success" title="Generated by a Featherless.ai model">Featherless AI · {model}</span>
    : <span className="badge badge-demo" title="Scripted rules; no AI model was called (no Featherless key configured)">
        Deterministic demo mode · not AI
      </span>;
}

export function Notice({ tone, children }: { tone: 'info' | 'warn' | 'error' | 'demo' | 'ok'; children: ReactNode }) {
  return <div className={`notice notice-${tone}`}>{children}</div>;
}

export function CoveragePanel({ coverage, compact = false }: { coverage: Coverage; compact?: boolean }) {
  const cacheText = {
    cached: 'Served from local cache',
    cached_after_failed_refresh: 'Latest refresh failed; showing cached real records',
    no_data: 'No source records stored',
  }[coverage.cache_status];
  return (
    <div className="stack-sm">
      <div className="row">
        <Database size={15} color="#93C5FD" />
        <span className="small secondary">{coverage.label}</span>
      </div>
      <div className="row small">
        <span className="chip">{coverage.row_count} source rows</span>
        <span className="chip">{coverage.observed_min_date ?? '?'} → {coverage.observed_max_date ?? '?'}</span>
        <span className={`badge ${coverage.complete ? 'badge-success' : 'badge-high'}`}>
          {coverage.complete ? 'Complete retrieval' : 'Incomplete retrieval'}
        </span>
        {coverage.cache_status !== 'cached' && <span className="badge badge-high">{cacheText}</span>}
      </div>
      {!compact && (
        <>
          {coverage.last_error && <Notice tone="warn">{coverage.last_error}</Notice>}
          <p className="small muted">{coverage.historical_note}</p>
          <div className="row">
            <a className="link" href={coverage.dataset_url} target="_blank" rel="noreferrer">Dataset page <ExternalLink size={11} /></a>
            <a className="link" href={coverage.api_query_url} target="_blank" rel="noreferrer">Filtered API query <ExternalLink size={11} /></a>
          </div>
        </>
      )}
    </div>
  );
}

const FIELD_LABELS: [string, string][] = [
  ['created_date', 'Record created'], ['category', 'Category'], ['short_description', 'Description'],
  ['ordinance', 'Ordinance'], ['source_status', 'Source status'], ['deadline_date', 'Historical deadline'],
  ['checkback_date', 'Historical check-back'], ['service_request_id', 'Service request'],
  ['count_of_violations', 'Count of violations'], ['received_method', 'Received via'],
];

export function EvidenceRecordView({ record }: { record: SourceRecord }) {
  const [showRaw, setShowRaw] = useState(false);
  const f = record.fields;
  return (
    <div className="record stack-sm">
      <div className="row-between">
        <div className="row small">
          <span className="chip">E{record.evidence_id}</span>
          <span className="secondary">{record.resource_label} row {record.source_row_id}</span>
          {record.case_id && <span className="chip">case {record.case_id}</span>}
          {record.violation_id && <span className="chip">violation {record.violation_id}</span>}
        </div>
        <a className="link" href={record.source_url} target="_blank" rel="noreferrer">Source row <ExternalLink size={11} /></a>
      </div>
      <dl className="kv">
        {FIELD_LABELS.filter(([k]) => f[k]).map(([k, label]) => (
          <div key={k} style={{ display: 'contents' }}><dt>{label}</dt><dd>{f[k]}</dd></div>
        ))}
        <dt>Retrieved</dt><dd>{formatTime(record.fetched_at)}</dd>
      </dl>
      {f.notes && <div className="notes-text">{f.notes}</div>}
      <button className="link" style={{ alignSelf: 'flex-start' }} onClick={() => setShowRaw(!showRaw)}>
        {showRaw ? 'Hide original fields' : 'Show original fields'}
      </button>
      {showRaw && (
        <table className="data mono">
          <tbody>
            {Object.entries(record.raw).map(([k, v]) => (
              <tr key={k}><th>{k}</th><td style={{ whiteSpace: 'pre-wrap' }}>{v === null ? '∅ (missing)' : String(v)}</td></tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export function EvidenceIds({ ids, label = 'Evidence' }: { ids: number[]; label?: string }) {
  const [open, setOpen] = useState(false);
  const [records, setRecords] = useState<SourceRecord[] | null>(null);
  const [error, setError] = useState('');

  const toggle = async () => {
    const next = !open;
    setOpen(next);
    if (next && !records) {
      try {
        setRecords(await api.evidence(ids));
      } catch (e) {
        setError(errorMessage(e));
      }
    }
  };

  if (!ids.length) return <span className="small muted">No evidence cited.</span>;
  return (
    <div className="stack-sm">
      <div className="row small">
        <button className="btn btn-secondary btn-sm" onClick={toggle}>
          <FileSearch size={13} /> {label} ({ids.length}) {open ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
        </button>
        {ids.slice(0, 12).map((id) => <span key={id} className="chip">E{id}</span>)}
        {ids.length > 12 && <span className="muted">+{ids.length - 12}</span>}
      </div>
      {open && error && <Notice tone="error">{error}</Notice>}
      {open && !records && !error && <span className="small muted">Loading source records…</span>}
      {open && records?.map((r) => <EvidenceRecordView key={r.evidence_id} record={r} />)}
    </div>
  );
}

export function Empty({ children }: { children: ReactNode }) {
  return <div className="glass-panel panel small muted" style={{ textAlign: 'center' }}>{children}</div>;
}
